import Head from "next/head";

export const Header = () => {
  return (
    <Head>
      <title>DN Media Playlist</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
};
